### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by davidbonnet** [nevoland/realue#311]
Things to consider:
- [x] Specific error type (list of strings?)
- [x] Errors in arrays
- [x] Errors for compound values (arrays and object)
